from organism import Organism
from sheep import Sheep
from grass import Grass
from human import Human
from hogweed import Hogweed
from cybersheep import Cybersheep
from wolf import Wolf
from fox import Fox
from antylope import Antylope
from turtle import Turtle
from dandelion import Dandelion
from guarana import Guarana
from wolfberry import Wolfberry
